name: Deploy

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Dispatch CI
        uses: peter-evans/repository-dispatch@v2
        with:
          repository: memset0/gatsby-blog
          token: ${{ secrets.GH_TOKEN }}
          event-type: content-update
